import { initializeApp } from "https://www.gstatic.com/firebasejs/12.2.1/firebase-app.js";
import { getAuth, createUserWithEmailAndPassword, signInWithEmailAndPassword, sendEmailVerification, sendPasswordResetEmail, signOut, onAuthStateChanged } from "https://www.gstatic.com/firebasejs/12.2.1/firebase-auth.js";
import { getFirestore, doc, getDoc, setDoc, updateDoc, addDoc, collection, query, where, orderBy, onSnapshot, serverTimestamp, increment, limit, deleteDoc } from "https://www.gstatic.com/firebasejs/12.2.1/firebase-firestore.js";
import { getStorage, ref, uploadBytes, getDownloadURL } from "https://www.gstatic.com/firebasejs/12.2.1/firebase-storage.js";
import { firebaseConfig } from "./firebase-config.js";

const app=initializeApp(firebaseConfig), auth=getAuth(app), db=getFirestore(app), storage=getStorage(app);
let user=null, profile=null, registerMode=false, unsub=[];

const I={
uz:{login:"Kirish",register:"Ro‘yxatdan o‘tish",logout:"Chiqish",forgot:"Parolni unutdingizmi?",authSub:"PUBG Mobile UC uchun xavfsiz magazin",welcome:"Xush kelibsiz",hero:"UC xarid qiling, balansni boshqaring va buyurtmalaringizni kuzating.",balance:"Balans",shop:"UC Magazin",deposit:"Balans to‘ldirish",orders:"Buyurtmalar",support:"Yordam",packages:"UC paketlari",depositTitle:"Balans to‘ldirish",depositHelp:"Paynet yoki boshqa to‘lov orqali pul yuboring va chek rasmini yuklang.",sendReceipt:"Chekni yuborish",myOrders:"Mening buyurtmalarim",supportTitle:"Yordam",send:"Yuborish"},
ru:{login:"Войти",register:"Регистрация",logout:"Выйти",forgot:"Забыли пароль?",authSub:"Безопасный магазин PUBG Mobile UC",welcome:"Добро пожаловать",hero:"Покупайте UC, пополняйте баланс и отслеживайте заказы.",balance:"Баланс",shop:"Магазин UC",deposit:"Пополнить баланс",orders:"Заказы",support:"Поддержка",packages:"Пакеты UC",depositTitle:"Пополнение баланса",depositHelp:"Оплатите через Paynet или другой способ и загрузите чек.",sendReceipt:"Отправить чек",myOrders:"Мои заказы",supportTitle:"Поддержка",send:"Отправить"}
};
let lang=localStorage.lang||"uz";
function applyLang(){document.querySelectorAll("[data-i18n]").forEach(e=>e.textContent=I[lang][e.dataset.i18n]||e.textContent);langBtn.textContent=lang==="uz"?"RU":"UZ";localStorage.lang=lang}
const $=id=>document.getElementById(id);
$("langBtn").onclick=()=>{lang=lang==="uz"?"ru":"uz";applyLang()};
$("loginTab").onclick=()=>{registerMode=false; $("loginTab").classList.add("active");$("registerTab").classList.remove("active");$("authSubmit").textContent=I[lang].login};
$("registerTab").onclick=()=>{registerMode=true;$("registerTab").classList.add("active");$("loginTab").classList.remove("active");$("authSubmit").textContent=I[lang].register};
$("authForm").onsubmit=async e=>{e.preventDefault();$("authMsg").textContent="";try{if(registerMode){const c=await createUserWithEmailAndPassword(auth,$("email").value,$("password").value);await sendEmailVerification(c.user);await setDoc(doc(db,"users",c.user.uid),{email:c.user.email,role:"user",balance:0,createdAt:serverTimestamp()});$("authMsg").textContent="Emailingizga tasdiqlash havolasi yuborildi. Tasdiqlab, qayta kiring.";await signOut(auth)}else{const c=await signInWithEmailAndPassword(auth,$("email").value,$("password").value);if(!c.user.emailVerified){await sendEmailVerification(c.user);await signOut(auth);throw Error("Email tasdiqlanmagan. Yangi tasdiqlash xati yuborildi.")}}}catch(err){$("authMsg").textContent=err.message}};
$("forgotBtn").onclick=async()=>{try{await sendPasswordResetEmail(auth,$("email").value);$("authMsg").textContent="Parolni tiklash xati yuborildi."}catch(e){$("authMsg").textContent=e.message}};
$("logoutBtn").onclick=()=>signOut(auth);

onAuthStateChanged(auth,async u=>{user=u; if(!u){$("authView").classList.remove("hidden");$("appView").classList.add("hidden");$("logoutBtn").classList.add("hidden");return}
if(!u.emailVerified){await signOut(auth);return}
profile=(await getDoc(doc(db,"users",u.uid))).data();
$("authView").classList.add("hidden");$("appView").classList.remove("hidden");$("logoutBtn").classList.remove("hidden");
$("adminNav").classList.toggle("hidden",profile?.role!=="admin");loadAll()});

document.querySelectorAll(".navBtn").forEach(b=>b.onclick=()=>{document.querySelectorAll(".navBtn").forEach(x=>x.classList.remove("active"));b.classList.add("active");document.querySelectorAll(".page").forEach(x=>x.classList.add("hidden"));$(b.dataset.page+"Page").classList.remove("hidden");if(b.dataset.page==="admin")loadAdmin()});

function loadAll(){applyLang();onSnapshot(doc(db,"users",user.uid),s=>{profile=s.data();$("balance").textContent=(profile?.balance||0).toLocaleString()+" so‘m"});loadPackages();loadOrders();loadTickets()}
function loadPackages(){onSnapshot(query(collection(db,"packages"),orderBy("uc")),snap=>{$("packages").innerHTML="";snap.forEach(d=>{const p=d.data();$("packages").innerHTML+=`<div class="card glass"><div class="uc">🎮 ${p.uc} UC</div><div class="price">${p.price.toLocaleString()} so‘m</div><button class="primary buy" data-id="${d.id}">Sotib olish</button></div>`});document.querySelectorAll(".buy").forEach(b=>b.onclick=()=>buy(b.dataset.id))})}
async function buy(id){const p=(await getDoc(doc(db,"packages",id))).data();if((profile.balance||0)<p.price)return alert("Balans yetarli emas.");const pid=prompt("PUBG Player ID kiriting:");if(!pid)return;await updateDoc(doc(db,"users",user.uid),{balance:increment(-p.price)});await addDoc(collection(db,"orders"),{uid:user.uid,email:user.email,pubgId:pid,uc:p.uc,price:p.price,status:"pending",createdAt:serverTimestamp()});alert("Buyurtma qabul qilindi.")}
$("depositBtn").onclick=async()=>{const amount=Number($("depositAmount").value),file=$("depositReceipt").files[0];if(!amount||amount<1000||!file)return $("depositMsg").textContent="Summa va chekni kiriting.";const path=`receipts/${user.uid}/${Date.now()}_${file.name}`;const r=ref(storage,path);await uploadBytes(r,file);const url=await getDownloadURL(r);await addDoc(collection(db,"deposits"),{uid:user.uid,email:user.email,amount,receiptUrl:url,status:"pending",createdAt:serverTimestamp()});$("depositMsg").textContent="Chek yuborildi. Admin tekshiradi."};
$("supportBtn").onclick=async()=>{const text=$("supportText").value.trim();if(!text)return;await addDoc(collection(db,"tickets"),{uid:user.uid,email:user.email,messages:[{from:"user",text,at:new Date().toISOString()}],status:"open",createdAt:serverTimestamp()});$("supportText").value="";$("supportMsg").textContent="Xabar yuborildi."};
function loadOrders(){onSnapshot(query(collection(db,"orders"),where("uid","==",user.uid),orderBy("createdAt","desc")),s=>{$("orders").innerHTML=s.empty?"Buyurtma yo‘q.":s.docs.map(d=>{let x=d.data();return `<div class="order">🎮 ${x.uc} UC — ${x.price.toLocaleString()} so‘m<br>PUBG ID: ${x.pubgId}<br>Status: <b>${x.status}</b></div>`}).join("")})}
function loadTickets(){onSnapshot(query(collection(db,"tickets"),where("uid","==",user.uid),orderBy("createdAt","desc")),s=>{$("tickets").innerHTML=s.docs.map(d=>{let x=d.data();return `<div class="ticket"><b>${x.status}</b>${(x.messages||[]).map(m=>`<p><b>${m.from}:</b> ${m.text}</p>`).join("")}</div>`}).join("")})}
async function loadAdmin(){if(profile?.role!=="admin")return;onSnapshot(query(collection(db,"packages"),orderBy("uc")),s=>{$("adminPackages").innerHTML=s.docs.map(d=>{let x=d.data();return `<div class="admin-item">${x.uc} UC — ${x.price.toLocaleString()} so‘m <button class="smallBtn delp" data-id="${d.id}">O‘chirish</button></div>`}).join("");document.querySelectorAll(".delp").forEach(b=>b.onclick=()=>deleteDoc(doc(db,"packages",b.dataset.id)))});onSnapshot(query(collection(db,"deposits"),where("status","==","pending"),orderBy("createdAt","desc")),s=>{$("adminDeposits").innerHTML=s.docs.map(d=>{let x=d.data();return `<div class="admin-item">${x.email}<br>${x.amount.toLocaleString()} so‘m<br><a href="${x.receiptUrl}" target="_blank">Chekni ko‘rish</a><br><button class="smallBtn approveDep" data-id="${d.id}">Tasdiqlash</button><button class="smallBtn rejectDep" data-id="${d.id}">Rad etish</button></div>`}).join("");document.querySelectorAll(".approveDep").forEach(b=>b.onclick=()=>approveDeposit(b.dataset.id));document.querySelectorAll(".rejectDep").forEach(b=>b.onclick=()=>updateDoc(doc(db,"deposits",b.dataset.id),{status:"rejected"}))});onSnapshot(query(collection(db,"orders"),where("status","==","pending"),orderBy("createdAt","desc")),s=>{$("adminOrders").innerHTML=s.docs.map(d=>{let x=d.data();return `<div class="admin-item">${x.email}<br>🎮 ${x.uc} UC — ID ${x.pubgId}<br><button class="smallBtn completeOrder" data-id="${d.id}">UC berildi</button></div>`}).join("");document.querySelectorAll(".completeOrder").forEach(b=>b.onclick=()=>updateDoc(doc(db,"orders",b.dataset.id),{status:"completed"}))});onSnapshot(query(collection(db,"tickets"),where("status","==","open"),orderBy("createdAt","desc")),s=>{$("adminTickets").innerHTML=s.docs.map(d=>{let x=d.data();return `<div class="admin-item">${x.email}${(x.messages||[]).map(m=>`<p><b>${m.from}:</b> ${m.text}</p>`).join("")}<input id="reply-${d.id}" placeholder="Javob"><button class="smallBtn reply" data-id="${d.id}">Javob berish</button></div>`}).join("");document.querySelectorAll(".reply").forEach(b=>b.onclick=async()=>{const d=await getDoc(doc(db,"tickets",b.dataset.id)),x=d.data();const text=$("reply-"+b.dataset.id).value.trim();if(!text)return;await updateDoc(doc(db,"tickets",b.dataset.id),{messages:[...(x.messages||[]),{from:"admin",text,at:new Date().toISOString()}],status:"answered"})})})}
async function approveDeposit(id){const d=await getDoc(doc(db,"deposits",id)),x=d.data();await updateDoc(doc(db,"users",x.uid),{balance:increment(x.amount)});await updateDoc(doc(db,"deposits",id),{status:"approved"})}
$("addPackageBtn").onclick=async()=>{const uc=Number($("ucAmount").value),price=Number($("ucPrice").value);if(!uc||!price)return;await addDoc(collection(db,"packages"),{uc,price,createdAt:serverTimestamp()});$("ucAmount").value="";$("ucPrice").value=""};
applyLang();
